name: api_kit
description: "Production-ready REST API framework with comprehensive JWT authentication system, custom validators, annotation-based routing, token blacklisting, etc."
version: 0.0.4
homepage: https://github.com/jhonacodes/api_kit
repository: https://github.com/jhonacodes/api_kit
issue_tracker: https://github.com/jhonacodes/api_kit/issues
documentation: https://github.com/jhonacodes/api_kit/blob/main/README.md

topics:
  - api
  - server
  - http
  - jwt
  - middleware

platforms:
  linux:
  macos:
  windows:
  web:

environment:
  sdk: ">=3.9.0 <4.0.0"

dependencies:
  # Core Shelf dependencies (official Dart)
  shelf: ^1.4.1
  shelf_router: ^1.1.4
  
  # HTTP client (official Dart)
  http: ^1.5.0
  
  # Logging (external but specified by user)
  logger_rs: ^1.0.3
  
  # Result handling (user specified)
  result_controller: ^1.3.0
  
  # Core Dart libraries
  convert: ^3.1.1

dev_dependencies:
  # Testing
  test: ^1.25.6
  
  # Linting and analysis
  lints: ^6.0.0
  
  # Coverage
  coverage: ^1.7.2
